name: Jiaqi Li
url: http://www.jiaqili.com
markdown: redcarpet
redcarpet:
  extensions: [hard_wrap]
pygments: true
permalink: date
author: Jiaqi Li
exclude: [s3_website.yml, README.md]
timezone: America/New_York
