markdown: rdiscount
highlighter: pygments
permalink: date
rdiscount:
  extensions: [smart]
title : Jiaqi Li
production_url : http://jiaqili.com
analytics: UA-3936326-3
exclude: [s3_website.yml, readme.markdown, CNAME, Gemfile, Gemfile.lock, LICENSE, Makefile, package.json, Rakefile]
timezone: America/New_York
paginate: 10
author :
  name : Jiaqi Li
  twitter : jiaqili
  linkedin : jiaqili
  facebook : jiaqili
